export interface MutualFund {
  id: string;
  name: string;
  category: string;
  subCategory: string;
  aum: number; // in crores
  expenseRatio: number; // percentage
  oneYearReturn: number;
  threeYearReturn: number;
  fiveYearReturn: number;
  riskLevel: "Low" | "Moderate" | "High" | "Very High";
}

export const MUTUAL_FUNDS: MutualFund[] = [
  {
    id: "mirae-large-cap",
    name: "Mirae Asset Large Cap Fund",
    category: "Equity",
    subCategory: "Large Cap",
    aum: 36500,
    expenseRatio: 0.54,
    oneYearReturn: 18.2,
    threeYearReturn: 14.5,
    fiveYearReturn: 16.8,
    riskLevel: "High",
  },
  {
    id: "parag-parikh-flexi",
    name: "Parag Parikh Flexi Cap Fund",
    category: "Equity",
    subCategory: "Flexi Cap",
    aum: 58200,
    expenseRatio: 0.63,
    oneYearReturn: 22.1,
    threeYearReturn: 18.9,
    fiveYearReturn: 21.3,
    riskLevel: "High",
  },
  {
    id: "axis-elss",
    name: "Axis ELSS Tax Saver Fund",
    category: "Equity",
    subCategory: "ELSS",
    aum: 32100,
    expenseRatio: 0.62,
    oneYearReturn: 16.4,
    threeYearReturn: 12.8,
    fiveYearReturn: 15.2,
    riskLevel: "High",
  },
  {
    id: "hdfc-midcap",
    name: "HDFC Mid-Cap Opportunities Fund",
    category: "Equity",
    subCategory: "Mid Cap",
    aum: 61500,
    expenseRatio: 0.81,
    oneYearReturn: 28.6,
    threeYearReturn: 24.3,
    fiveYearReturn: 22.1,
    riskLevel: "Very High",
  },
  {
    id: "nippon-small-cap",
    name: "Nippon India Small Cap Fund",
    category: "Equity",
    subCategory: "Small Cap",
    aum: 48900,
    expenseRatio: 0.68,
    oneYearReturn: 32.4,
    threeYearReturn: 28.7,
    fiveYearReturn: 26.9,
    riskLevel: "Very High",
  },
  {
    id: "sbi-nifty50-index",
    name: "SBI Nifty 50 Index Fund",
    category: "Equity",
    subCategory: "Index Fund",
    aum: 21800,
    expenseRatio: 0.19,
    oneYearReturn: 16.9,
    threeYearReturn: 13.2,
    fiveYearReturn: 14.8,
    riskLevel: "High",
  },
  {
    id: "icici-liquid",
    name: "ICICI Prudential Liquid Fund",
    category: "Debt",
    subCategory: "Liquid",
    aum: 42300,
    expenseRatio: 0.2,
    oneYearReturn: 7.1,
    threeYearReturn: 5.8,
    fiveYearReturn: 5.6,
    riskLevel: "Low",
  },
  {
    id: "kotak-flexi-cap",
    name: "Kotak Flexi Cap Fund",
    category: "Equity",
    subCategory: "Flexi Cap",
    aum: 45600,
    expenseRatio: 0.59,
    oneYearReturn: 19.8,
    threeYearReturn: 15.6,
    fiveYearReturn: 17.4,
    riskLevel: "High",
  },
  {
    id: "quant-small-cap",
    name: "Quant Small Cap Fund",
    category: "Equity",
    subCategory: "Small Cap",
    aum: 18700,
    expenseRatio: 0.62,
    oneYearReturn: 38.2,
    threeYearReturn: 34.6,
    fiveYearReturn: 31.8,
    riskLevel: "Very High",
  },
  {
    id: "uti-nifty50-index",
    name: "UTI Nifty 50 Index Fund",
    category: "Equity",
    subCategory: "Index Fund",
    aum: 19200,
    expenseRatio: 0.2,
    oneYearReturn: 16.8,
    threeYearReturn: 13.1,
    fiveYearReturn: 14.7,
    riskLevel: "High",
  },
  {
    id: "dsp-midcap",
    name: "DSP Midcap Fund",
    category: "Equity",
    subCategory: "Mid Cap",
    aum: 19800,
    expenseRatio: 0.71,
    oneYearReturn: 24.9,
    threeYearReturn: 21.3,
    fiveYearReturn: 19.6,
    riskLevel: "Very High",
  },
  {
    id: "motilal-nasdaq100",
    name: "Motilal Oswal Nasdaq 100 Fund",
    category: "International",
    subCategory: "US Equity",
    aum: 12400,
    expenseRatio: 0.58,
    oneYearReturn: 26.4,
    threeYearReturn: 14.2,
    fiveYearReturn: 22.8,
    riskLevel: "Very High",
  },
  {
    id: "hdfc-balanced-advantage",
    name: "HDFC Balanced Advantage Fund",
    category: "Hybrid",
    subCategory: "Balanced Advantage",
    aum: 87400,
    expenseRatio: 0.74,
    oneYearReturn: 14.6,
    threeYearReturn: 12.4,
    fiveYearReturn: 13.8,
    riskLevel: "Moderate",
  },
  {
    id: "sbi-small-cap",
    name: "SBI Small Cap Fund",
    category: "Equity",
    subCategory: "Small Cap",
    aum: 26700,
    expenseRatio: 0.65,
    oneYearReturn: 29.8,
    threeYearReturn: 25.4,
    fiveYearReturn: 23.6,
    riskLevel: "Very High",
  },
  {
    id: "axis-bluechip",
    name: "Axis Bluechip Fund",
    category: "Equity",
    subCategory: "Large Cap",
    aum: 34500,
    expenseRatio: 0.57,
    oneYearReturn: 14.8,
    threeYearReturn: 11.2,
    fiveYearReturn: 14.4,
    riskLevel: "High",
  },
  {
    id: "icici-pru-nifty50",
    name: "ICICI Prudential Nifty 50 Index Fund",
    category: "Equity",
    subCategory: "Index Fund",
    aum: 8900,
    expenseRatio: 0.17,
    oneYearReturn: 17.0,
    threeYearReturn: 13.3,
    fiveYearReturn: 14.9,
    riskLevel: "High",
  },
  {
    id: "franklin-prima-plus",
    name: "Franklin India Prima Plus Fund",
    category: "Equity",
    subCategory: "Multi Cap",
    aum: 9200,
    expenseRatio: 0.95,
    oneYearReturn: 17.6,
    threeYearReturn: 14.9,
    fiveYearReturn: 16.2,
    riskLevel: "High",
  },
  {
    id: "invesco-india-multicap",
    name: "Invesco India Multicap Fund",
    category: "Equity",
    subCategory: "Multi Cap",
    aum: 4100,
    expenseRatio: 0.67,
    oneYearReturn: 25.4,
    threeYearReturn: 22.1,
    fiveYearReturn: 20.8,
    riskLevel: "Very High",
  },
  {
    id: "mirae-emerging-bluechip",
    name: "Mirae Asset Emerging Bluechip Fund",
    category: "Equity",
    subCategory: "Large & Mid Cap",
    aum: 32600,
    expenseRatio: 0.59,
    oneYearReturn: 21.3,
    threeYearReturn: 18.7,
    fiveYearReturn: 19.4,
    riskLevel: "Very High",
  },
  {
    id: "ppfas-tax-saver",
    name: "PPFAS Tax Saver Fund",
    category: "Equity",
    subCategory: "ELSS",
    aum: 2800,
    expenseRatio: 0.71,
    oneYearReturn: 20.8,
    threeYearReturn: 17.2,
    fiveYearReturn: 19.1,
    riskLevel: "High",
  },
];

export const FUND_CATEGORIES = [
  "Large Cap",
  "Mid Cap",
  "Small Cap",
  "Flexi Cap",
  "Multi Cap",
  "Large & Mid Cap",
  "ELSS",
  "Index Fund",
  "Balanced Advantage",
  "Liquid",
  "US Equity",
];
